### PR TITLE
Change dice roll output to show individual rolls

### PR DESCRIPTION
**Pull request by jmhossler**
I'm sorry about the tab changes.. I didn't realize before that you were using tab, so I tried to make the best of it. I'm fine with wiping these changes.

Also, I know this was made a bit ago but.. it should probably have tests somewhere.

Here is an example of the dice output with these changes.
```
Homer - Dungeon Master's Shell
> dice 4 7
4 1 6 6
Total: 17
```

### CODE REVIEW

**Comment by jmhossler** [comment]
This should address some of #1, though only somewhat.

**Comment by jmhossler** [comment]
oh god, the spacing is so horrible.. I wonder if I can fix it so the diff is only the code changes.

**Comment by gnossen** [comment]
As long as the substantive changes are in a separate commit from the formatting changes, it should be fine. But fwiw, `go fmt` should decide on the formatting. I last touched this so long ago that I'm not sure if I was using it or not.

Edit: I was using it. [This is the official style for Golang code.](https://golang.org/doc/effective_go.html#formatting) So the tabs should stay.

**Comment by jmhossler** [comment]
I completely forgot that I didn't have vim-go installed anymore. I was just assuming the formatter was running but didn't care. should be updated now with go fmt.

**Pull request merged**
